### ISSUE TITLE
404 on landing page

### ISSUE THREAD

**Issue by maestrofx** [Massad/gin-boilerplate#4]
Hi @Massad , just take a look a good Gin boilerplate for my project and found this interesting!
But, got 404 when hit the http://localhost:9000/?
Any help! Thank you.

**Comment by Massad** [comment]
Hi @maestrofx, you can check the requests from this [import-postman-collection-apis](https://github.com/Massad/gin-boilerplate#import-postman-collection-apis) or [http://localhost:9000/v1/articles](http://localhost:9000/v1/articles) as I didn't implement an HTML sample page; but it's a good idea to add one later on as an example for a landing page since I only included API's requests examples only.

**Comment by maestrofx** [comment]
Yes, still playing with this boilerplate... I think it's because of the sessionUser..

**Comment by Massad** [comment]
@maestrofx check this commit [https://github.com/Massad/gin-boilerplate/commit/b53f3d8bb7b0daaf121c29547243573947dfb291](https://github.com/Massad/gin-boilerplate/commit/b53f3d8bb7b0daaf121c29547243573947dfb291) just updated it.
