### ISSUE TITLE
Doesnt hit the create article endpoint

### ISSUE THREAD

**Issue by h4ck3rk3y** [Massad/gin-boilerplate#9]
https://github.com/Massad/gin-boilerplate/blob/19bc7539f80228bbbffbe5d95ccc97b94dc71ed4/tests/article_test.go#L377-L398

**Comment by Massad** [comment]
![Screen Shot 2020-05-24 at 3 03 48 PM](https://user-images.githubusercontent.com/3076722/82752543-d7a61b80-9dcf-11ea-947f-153296b759b6.png)

It does reach it, can you please explain more?

**Comment by Massad** [comment]
![Screen Shot 2020-05-24 at 3 05 08 PM](https://user-images.githubusercontent.com/3076722/82752573-fefce880-9dcf-11ea-832e-0e40d7f84f34.png)

It does reach it, can you please explain more?

**Comment by h4ck3rk3y** [comment]
Oh sorry I was a bit confused because of the name `TestCreateArticleUnauthorized`. I was expecting a `POST` request to the `/v1/article` endpoint with an invalid token. This is a Get request though. `TestGetArticleUnauthorized` might be a better name?

**Comment by Massad** [comment]
You are absolutely correct! At first it was for "Creation" but then changed to "Get" because doesn't make sense to validate it post with body request... GET is less code.

Changed it here [https://github.com/Massad/gin-boilerplate/commit/38835a58592b37980589806e56faaa720cde63ed](https://github.com/Massad/gin-boilerplate/commit/38835a58592b37980589806e56faaa720cde63ed)

**Comment by endyk** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Test      Sent via BlackBerry Hub+ Inbox for Android
